// Code generated by struct2interface; DO NOT EDIT.

package testdata

// PackageMethodInterface ...
type PackageMethodInterface interface {
	Method1() string
	Method2() string
}

// PackageMethod2Interface ...
type PackageMethod2Interface interface {
	Method1() string
}
