package main

import (
	"github.com/hnlq715/struct2interface"
	"github.com/spf13/cobra"
)

func main() {
	var (
		dir, PkgName, IfaceName, Comment, Output string
	)

	root := &cobra.Command{
		Use: "struct2interface",
		RunE: func(cmd *cobra.Command, args []string) error {
			return struct2interface.MakeDir(dir)
		},
	}

	root.Flags().StringVarP(&dir, "dir", "d", "", "Go source file to read, either dir or glob")
	root.Flags().StringVarP(&IfaceName, "iface", "i", "", "Name of the generated interface")
	root.Flags().StringVarP(&PkgName, "pkg", "p", "", "Package name for the generated interface")
	root.Flags().StringVarP(&Comment, "comment", "c", "", "Append comment to top, default is '// Code generated by ifacemaker; DO NOT EDIT.'\"")
	root.Flags().StringVarP(&Output, "output", "o", "", "Output file name. If not provided, result will be printed to stdout.")
	root.Execute()

}
