// Code generated by struct2interface; DO NOT EDIT.

package testdata

// Method1Interface ...
// Method1 describes the code and documentation
// tied into a method
type Method1Interface interface {
	// Lines return a []string consisting of
	// the documentation and code appended
	// in chronological order
	Lines() []string
}
